env:
  EXTNAME: skeleton

language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - travis
  - /^v\d+\.\d+\.\d+$/

install:
  - phpize
  - ./configure
  - make

before_script:
  make install

script:
  make test

after_failure:
  - |
    for FILE in $(find tests -name '*.diff'); do
      echo $FILE
      cat FILE
      echo
    done

before_deploy:
  - pecl package
  - export RELEASE_PACKAGE=$(ls "$EXTNAME"-*.tgz)

deploy:
  provider: releases
  api_key:
    secure: "Your encrypted GitHub API key"
  file: "$RELEASE_PACKAGE"
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  prerelease: true
  on:
    tags: true

